export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';
export const SET_CURRENT = 'SET_CURRENT';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
